version: "3"
services:
  webservice:
    image: webservice:2.1.6.RELEASE
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - hostonly
    volumes:
      - "logdata:/tmp"
    tty: true
    stdin_open: true
  appservice:
    image: appservice:2.1.6.RELEASE
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      - hostonly
    volumes:
      - "logdata:/tmp"
    tty: true
    stdin_open: true
networks:
  hostonly:
volumes:
  logdata:
